spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8081
          predicates:
            - Path=/orders,/orders/**

        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory,/inventory/**

server:
  port: 8080