spring.application.name=user-service
server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/quickcommerce
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=user_service

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

jwt.secret=yourSecretKeyyourSecretKeyyourSecretKey123456
jwt.expiration=3600000